### ISSUE TITLE
一个报错

### ISSUE THREAD

**Issue by sgyueran** [Yooooran/auto_attend_meeting#1]
我不太懂python，可以寻求下帮助嘛，谢谢大佬

Traceback (most recent call last):
  File "C:\Users\15335\Desktop\meetings-auto-participate-main\main.py", line 74, in <module>
    enter_meeting(meeting_id, passcode, df_way)
  File "C:\Users\15335\Desktop\meetings-auto-participate-main\main.py", line 29, in enter_meeting
    click("enter_meeting.png")
  File "C:\Users\15335\Desktop\meetings-auto-participate-main\main.py", line 11, in click
    enter_mt_btn = pyautogui.locateCenterOnScreen(img)
  File "C:\Users\15335\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui-0.9.53-py3.10.egg\pyautogui\__init__.py", line 175, in wrapper
  File "C:\Users\15335\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui-0.9.53-py3.10.egg\pyautogui\__init__.py", line 207, in locateCenterOnScreen
  File "C:\Users\15335\AppData\Local\Programs\Python\Python310\lib\site-packages\pyscreeze-0.1.28-py3.10.egg\pyscreeze\__init__.py", line 413, in locateCenterOnScreen
  File "C:\Users\15335\AppData\Local\Programs\Python\Python310\lib\site-packages\pyscreeze-0.1.28-py3.10.egg\pyscreeze\__init__.py", line 372, in locateOnScreen
  File "C:\Users\15335\AppData\Local\Programs\Python\Python310\lib\site-packages\pyscreeze-0.1.28-py3.10.egg\pyscreeze\__init__.py", line 144, in wrapper
pyscreeze.PyScreezeException: The Pillow package is required to use this function.

**Comment by Yooooran** [comment]
在python终端中输入：
`pip install pillow`
试一下

**Comment by sgyueran** [comment]
奇怪的报错增加了
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\meetings-auto-participate-main\main.py", line 46, in <module>
    df = pd.read_excel(r"timings.xlsx")
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 457, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 1376, in __init__
    ext = inspect_excel_format(
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 1250, in inspect_excel_format
    with get_handle(
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\common.py", line 798, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'timings.xlsx'

**Comment by sgyueran** [comment]
奇怪的报错增加了
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\meetings-auto-participate-main\main.py", line 46, in <module>
    df = pd.read_excel(r"timings.xlsx")
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 457, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 1376, in __init__
    ext = inspect_excel_format(
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 1250, in inspect_excel_format
    with get_handle(
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\common.py", line 798, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'timings.xlsx'

**Comment by sgyueran** [comment]
我补全了一下我的插件，发现可以正常运行了，但是会发生点不到加入会议等坐标识别问题

**Comment by Yooooran** [comment]
不好意思，我是在自己的腾讯/Zoom会议软件里面截图的，我猜测可能会因为分辨率、软件版本不同的问题造成误识别，或许需要重新截图覆盖原来的图片
